In [36]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [85]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [86]:
movies = pd.read_csv(r"C:\Users\user\Desktop\extractedNumpy\Movie+Assignment+Data.csv")

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [87]:
movies.shape
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [88]:
a1=len(movies.index)
a1

5043

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [89]:
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [90]:

movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [91]:
a=round((movies.isnull().sum()/len(movies.index))*100,2)
a

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [92]:
movies=movies.drop(['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name',
 'duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio','plot_keywords'],axis=1)

# writing a code for percentage of column wise after removing the rows (which are not needed)
a=round((movies.isnull().sum()/len(movies.index))*100,2)
a

director_name              2.06
num_critic_for_reviews     0.99
gross                     17.53
genres                     0.00
actor_1_name               0.14
movie_title                0.00
num_voted_users            0.00
num_user_for_reviews       0.42
language                   0.24
budget                     9.76
title_year                 2.14
imdb_score                 0.00
movie_facebook_likes       0.00
dtype: float64

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [93]:
movies=movies[~np.isnan(movies['gross'])]
#again caculating the percentage 
a=round((movies.isnull().sum()/len(movies.index))*100,2)
a

#removing rows for budget
movies=movies[~np.isnan(movies['budget'])]
#again caculating the percentage 
a=round((movies.isnull().sum()/len(movies.index))*100,2)
a

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [94]:

movies[movies.isnull().sum(axis=1)>5]
# norows as scuch

Empty DataFrame
Columns: [director_name, num_critic_for_reviews, gross, genres, actor_1_name, movie_title, num_voted_users, num_user_for_reviews, language, budget, title_year, imdb_score, movie_facebook_likes]
Index: []

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [95]:

movies.loc[pd.isnull(movies['language']), ['language']] = 'English'
# checking the percantage again
round((movies.isnull().sum()/len(movies.index))*100,2)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.00
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [96]:
# this will tell the length 

(len(movies.index)/a1)*100

77.15645449137418

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [97]:
# Write your code for unit conversion her
movies['gross'] = movies['gross']/1000000
movies['budget'] = movies['budget']/1000000
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0000,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0000,2007.0,7.1,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0000,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0000,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7000,2012.0,6.6,24000
6,Sam Raimi,392.0,336.530303,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,1902.0,English,258.0000,2007.0,6.2,0
7,Nathan Greno,324.0,200.807262,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,387.0,English,260.0000,2010.0,7.8,29000
8,Joss Whedon,635.0,458.991599,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,1117.0,English,250.0000,2015.0,7.5,118000
9,David Yates,375.0,301.956980,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,973.0,English,250.0000,2009.0,7.5,10000
10,Zack Snyder,673.0,330.249062,Action|Adventure|Sci-Fi,Henry Cavill,Batman v Superman: Dawn of Justice,371639,3018.0,English,250.0000,2016.0,6.9,197000
11,Bryan Singer,434.0,200.069408,Action|Adventure|Sci-Fi,Kevin Spacey,Superman Returns,240396,2367.0,English,209.0000,2006.0,6.1,0
12,Marc Forster,403.0,168.368427,Action|Adventure,Giancarlo Giannini,Quantum of Solace,330784,1243.0,English,200.0000,2008.0,6.7,0
13,Gore Verbinski,313.0,423.032628,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: Dead Man's Chest,522040,1832.0,English,225.0000,2006.0,7.3,5000
14,Gore Verbinski,450.0,89.289910,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.0000,2013.0,6.5,48000
15,Zack Snyder,733.0,291.021565,Action|Adventure|Fantasy|Sci-Fi,Henry Cavill,Man of Steel,548573,2536.0,English,225.0000,2013.0,7.2,118000
16,Andrew Adamson,258.0,141.614023,Action|Adventure|Family|Fantasy,Peter Dinklage,The Chronicles of Narnia: Prince Caspian,149922,438.0,English,225.0000,2008.0,6.6,0
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0000,2012.0,8.1,123000
18,Rob Marshall,448.0,241.063875,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: On Stranger Tides,370704,484.0,English,250.0000,2011.0,6.7,58000
19,Barry Sonnenfeld,451.0,179.020854,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,Will Smith,Men in Black 3,268154,341.0,English,225.0000,2012.0,6.8,40000
20,Peter Jackson,422.0,255.108370,Adventure|Fantasy,Aidan Turner,The Hobbit: The Battle of the Five Armies,354228,802.0,English,250.0000,2014.0,7.5,65000
21,Marc Webb,599.0,262.030663,Action|Adventure|Fantasy,Emma Stone,The Amazing Spider-Man,451803,1225.0,English,230.0000,2012.0,7.0,56000
22,Ridley Scott,343.0,105.219735,Action|Adventure|Drama|History,Mark Addy,Robin Hood,211765,546.0,English,200.0000,2010.0,6.7,17000
23,Peter Jackson,509.0,258.355354,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.0000,2013.0,7.9,83000
24,Chris Weitz,251.0,70.083519,Adventure|Family|Fantasy,Christopher Lee,The Golden Compass,149019,666.0,English,180.0000,2007.0,6.1,0
25,Peter Jackson,446.0,218.051260,Action|Adventure|Drama|Romance,Naomi Watts,King Kong,316018,2618.0,English,207.0000,2005.0,7.2,0
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0000,1997.0,7.7,26000
27,Anthony Russo,516.0,407.197282,Action|Adventure|Sci-Fi,Robert Downey Jr.,Captain America: Civil War,272670,1022.0,English,250.0000,2016.0,8.2,72000
28,Peter Berg,377.0,65.173160,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.0000,2012.0,5.9,44000
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0000,2015.0,7.0,150000
30,Sam Mendes,750.0,304.360277,Action|Adventure|Thriller,Albert Finney,Skyfall,522030,1498.0,English,200.0000,2012.0,7.8,80000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4959,Robert Townsend,21.0,5.228617,Comedy,Robert Townsend,Hollywood Shuffle,2770,32.0,English,0.1000,1987.0,7.0,471
4962,Larry Blamire,88.0,0.110536,Comedy|Horror|Sci-Fi,Fay Masterson,The Lost Skeleton of Cadavra,4117,118.0,English,0.0400,2001.0,7.0,0
4964,E.L. Katz,193.0,0.059379,Comedy|Crime|Drama|Horror|Thriller,Brighton Sharbino,Cheap Thrills,12796,52.0,English,0.2000,2013.0,6.8,0
4971,Dennis Iliadis,241.0,32.721635,Crime|Horror|Thriller,Tony Goldwyn,The Last House on the Left,67824,279.0,English,15.0000,2009.0,6.6,0
4973,Darren Aronofsky,138.0,3.216970,Drama|Mystery|Thriller,Mark Margolis,Pi,142619,586.0,English,0.0600,1998.0,7.5,24000
4975,Myles Berkowitz,32.0,0.536767,Biography|Comedy|Romance,Tia Carrere,20 Dates,1622,83.0,English,0.0600,1998.0,5.3,30
4977,Morgan Spurlock,193.0,11.529368,Comedy|Documentary|Drama,Chemeeka Walker,Super Size Me,85028,404.0,English,0.0650,2004.0,7.3,0
4978,Brandon Trost,66.0,0.040557,Comedy,Clifton Collins Jr.,The FP,1389,22.0,English,0.0600,2011.0,5.6,0
4979,Joe Swanberg,65.0,0.030084,Comedy|Drama,Anna Kendrick,Happy Christmas,5507,23.0,English,0.0700,2014.0,5.6,812
4984,Edward Burns,36.0,10.246600,Comedy|Drama|Romance,Shari Albert,The Brothers McMullen,6375,36.0,English,0.0250,1995.0,6.6,265
4987,Lena Dunham,113.0,0.389804,Comedy|Drama|Romance,Lena Dunham,Tiny Furniture,11816,35.0,English,0.0650,2010.0,6.3,0
4997,David Gordon Green,75.0,0.241816,Drama,Paul Schneider,George Washington,6246,76.0,English,0.0420,2000.0,7.5,451
4998,Kevin Jordan,21.0,0.277233,Comedy|Romance,Derick Martini,Smiling Fish & Goat on Fire,2631,26.0,English,0.0400,1999.0,7.6,0
5004,Mike Bruce,3.0,0.243768,Western,Joseph Campanella,The Legend of God's Gun,143,9.0,English,0.0300,2007.0,4.1,13
5008,Kevin Smith,136.0,3.151130,Comedy,Jason Mewes,Clerks,181749,615.0,English,0.2300,1994.0,7.8,0
5009,James Bidgood,8.0,0.008231,Drama|Fantasy,Don Brooks,Pink Narcissus,803,16.0,English,0.0270,1971.0,6.7,85
5011,Neil LaBute,80.0,2.856622,Comedy|Drama,Stacy Edwards,In the Company of Men,11550,197.0,English,0.0250,1997.0,7.3,489
5012,David Ayer,233.0,10.499968,Action|Crime|Drama|Thriller,Mireille Enos,Sabotage,47502,212.0,English,35.0000,2014.0,5.7,10000
5015,Richard Linklater,61.0,1.227508,Comedy|Drama,Tommy Pallotta,Slacker,15103,80.0,English,0.0230,1991.0,7.1,2000
5021,Jay Duplass,51.0,0.192467,Comedy|Drama|Romance,Mark Duplass,The Puffy Chair,4067,71.0,English,0.0150,2005.0,6.6,297
5023,Daryl Wein,22.0,0.076382,Romance,Zoe Lister-Jones,Breaking Upwards,1194,8.0,English,0.0150,2009.0,6.2,324
5025,John Waters,73.0,0.180483,Comedy|Crime|Horror,Divine,Pink Flamingos,16792,183.0,English,0.0100,1972.0,6.1,0
5026,Olivier Assayas,81.0,0.136007,Drama|Music|Romance,Maggie Cheung,Clean,3924,39.0,French,0.0045,2004.0,6.9,171
5027,Jafar Panahi,64.0,0.673780,Drama,Fereshteh Sadre Orafaiy,The Circle,4555,26.0,Persian,0.0100,2000.0,7.5,697
5029,Kiyoshi Kurosawa,78.0,0.094596,Crime|Horror|Mystery|Thriller,Kôji Yakusho,The Cure,6318,50.0,Japanese,1.0000,1997.0,7.4,817
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,0.0070,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,Cavite,589,35.0,English,0.0070,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,0.0070,1992.0,6.9,0
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,0.0090,2011.0,6.4,413
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with Drew,4285,84.0,English,0.0011,2004.0,6.6,456

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [98]:
# Write your code for creating the profit column here
movies['profit']=movies.gross - movies.budget

In [99]:
# Write your code for sorting the dataframe here
movies=movies.sort_values(by='profit',ascending=False)

In [100]:
#i have splitted into twoways forbetter understanding-top100 is just arandom name dont think it as a top 100 movies
top100 =pd.DataFrame(movies.sort_values(by='profit',ascending=False))

top10=pd.DataFrame(top100.head(10))
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [101]:
# Write your code for dropping duplicate values here 
""" inplace true means in this same dataframeonly ihave changed and removed duplicate"""
top10.drop_duplicates('director_name',inplace=True)

In [102]:
# Write code for repeating subtask 2 here
top10=top10.sort_values(by='profit',ascending=False)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [103]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDb_Top_250=pd.DataFrame(movies[movies.num_voted_users>25000].sort_values(by='imdb_score',ascending=False).head(250))
#calculatinglength
len(IMDb_Top_250.index)

#[k for k in IMDb_Top_250.indes]
#IMDb_Top_250.apply(lambda x.count():x+1)

IMDb_Top_250['rank'] = range(0, len(IMDb_Top_250.index))
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,rank
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.00,1994.0,9.3,108000,3.341469,0
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.00,1972.0,9.2,43000,128.821952,1
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.316061,2
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.00,1974.0,9.0,14000,44.300000,3
1874,Steven Spielberg,174.0,96.067179,Biography|Drama|History,Liam Neeson,Schindler's List,865020,1273.0,English,22.00,1993.0,8.9,41000,74.067179,4
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.900000,5
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.00,2003.0,8.9,16000,283.019252,6
3355,Quentin Tarantino,215.0,107.930000,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8.00,1994.0,8.9,45000,99.930000,7
270,Peter Jackson,297.0,313.837577,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Fellowship of the R...,1238746,5060.0,English,93.00,2001.0,8.8,21000,220.837577,8
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.00,1999.0,8.8,48000,-25.976605,9
2051,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.00,1980.0,8.8,17000,272.158751,10
836,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.00,1994.0,8.8,59000,274.691196,11
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.00,2010.0,8.8,175000,132.568851,12
3867,Milos Forman,149.0,112.000000,Drama,Scatman Crothers,One Flew Over the Cuckoo's Nest,680041,760.0,English,4.40,1975.0,8.7,32000,107.600000,13
4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.30,2002.0,8.7,28000,4.263397,14
340,Peter Jackson,294.0,340.478898,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Two Towers,1100446,2417.0,English,94.00,2002.0,8.7,10000,246.478898,15
1903,Martin Scorsese,192.0,46.836394,Biography|Crime|Drama,Robert De Niro,Goodfellas,728685,989.0,English,25.00,1990.0,8.7,25000,21.836394,16
4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.00,1954.0,8.7,11000,-1.730939,17
654,Lana Wachowski,313.0,171.383253,Action|Sci-Fi,Keanu Reeves,The Matrix,1217752,3646.0,English,63.00,1999.0,8.7,25000,108.383253,18
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.00,1977.0,8.7,33000,449.935665,19
648,Steven Spielberg,219.0,216.119491,Action|Drama|War,Tom Hanks,Saving Private Ryan,881236,2277.0,English,70.00,1998.0,8.6,22000,146.119491,20
4427,Charles Chaplin,120.0,0.163245,Comedy|Drama|Family,Paulette Goddard,Modern Times,143086,211.0,English,1.50,1936.0,8.6,0,-1.336755,21
2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.00,2001.0,8.6,28000,-8.950114,22
2158,Jonathan Demme,185.0,130.727000,Crime|Drama|Horror|Thriller,Anthony Hopkins,The Silence of the Lambs,887467,916.0,English,19.00,1991.0,8.6,40000,111.727000,23
3175,Tony Kaye,162.0,6.712241,Crime|Drama,Ethan Suplee,American History X,782437,1420.0,English,7.50,1998.0,8.6,35000,-0.787759,24
96,Christopher Nolan,712.0,187.991439,Adventure|Drama|Sci-Fi,Matthew McConaughey,Interstellar,928227,2725.0,English,165.00,2014.0,8.6,349000,22.991439,25
3592,Bryan Singer,162.0,23.272306,Crime|Drama|Mystery|Thriller,Kevin Spacey,The Usual Suspects,740918,1182.0,English,6.00,1995.0,8.6,28000,17.272306,26
1600,David Fincher,216.0,100.125340,Crime|Drama|Mystery|Thriller,Morgan Freeman,Se7en,1023511,1080.0,English,33.00,1995.0,8.6,39000,67.125340,27
296,Quentin Tarantino,765.0,162.804648,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.00,2012.0,8.5,199000,62.804648,28
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.00,2012.0,8.5,164000,198.130642,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.50,2004.0,7.9,0,-1.870242,220
3768,Duncan Jones,415.0,5.009677,Drama|Mystery|Sci-Fi,Kevin Spacey,Moon,260607,485.0,English,5.00,2009.0,7.9,47000,0.009677,221
3452,Paul Haggis,287.0,54.557348,Crime|Drama|Thriller,Don Cheadle,Crash,361169,1624.0,English,6.50,2004.0,7.9,18000,48.057348,222
3193,Paul Haggis,287.0,54.557348,Crime|Drama|Thriller,Don Cheadle,Crash,361169,1624.0,English,6.50,2004.0,7.9,18000,48.057348,223
89,Don Hall,384.0,222.487711,Action|Adventure|Animation|Comedy|Drama|Family...,Damon Wayans Jr.,Big Hero 6,279093,433.0,English,165.00,2014.0,7.9,41000,57.487711,224
4640,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.59,2007.0,7.9,14000,0.595783,225
4821,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157863,1191.0,English,0.30,1978.0,7.9,12000,46.700000,226
2619,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157857,1191.0,English,0.30,1978.0,7.9,12000,46.700000,227
23,Peter Jackson,509.0,258.355354,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.00,2013.0,7.9,83000,33.355354,228
716,Doug Liman,249.0,121.468960,Action|Mystery|Thriller,Matt Damon,The Bourne Identity,407601,849.0,English,60.00,2002.0,7.9,0,61.468960,229
162,Dean DeBlois,292.0,176.997107,Action|Adventure|Animation|Comedy|Family|Fantasy,Gerard Butler,How to Train Your Dragon 2,221128,343.0,English,145.00,2014.0,7.9,46000,31.997107,230
706,Quentin Tarantino,596.0,54.116191,Crime|Drama|Mystery|Thriller|Western,Craig Stark,The Hateful Eight,272839,1018.0,English,44.00,2015.0,7.9,114000,10.116191,231
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.00,2004.0,7.9,2000,-4.078262,232
2863,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.00,2006.0,7.9,5000,-5.246069,233
1813,Philip Kaufman,80.0,21.500000,Adventure|Drama|History,Dennis Quaid,The Right Stuff,45271,170.0,English,27.00,1983.0,7.9,0,-5.500000,234
845,Paul Greengrass,491.0,107.100855,Biography|Drama|Thriller,Tom Hanks,Captain Phillips,323353,527.0,English,55.00,2013.0,7.9,65000,52.100855,235
4931,John Carney,232.0,9.437933,Drama|Music|Romance,Glen Hansard,Once,90827,329.0,English,0.18,2007.0,7.9,26000,9.257933,236
3029,David O. Russell,410.0,93.571803,Biography|Drama|Sport,Christian Bale,The Fighter,275869,389.0,English,25.00,2010.0,7.9,36000,68.571803,237
1713,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101888,365.0,English,18.00,1989.0,7.9,0,8.830000,238
2418,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101889,365.0,English,18.00,1989.0,7.9,0,8.830000,239
3361,Jonathan Dayton,270.0,59.889948,Comedy|Drama,Steve Carell,Little Miss Sunshine,355810,889.0,English,8.00,2006.0,7.9,15000,51.889948,240
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.00,2009.0,7.9,33000,523.505847,241
1606,Nick Cassavetes,177.0,0.064286,Drama|Romance,Ryan Gosling,The Notebook,396396,1111.0,English,29.00,2004.0,7.9,57000,-28.935714,242
69,Jon Favreau,486.0,318.298180,Action|Adventure|Sci-Fi,Robert Downey Jr.,Iron Man,696338,1055.0,English,140.00,2008.0,7.9,10000,178.298180,243
2493,Yimou Zhang,283.0,0.084961,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.00,2002.0,7.9,0,-30.915039,244
1171,Yimou Zhang,283.0,0.084961,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.00,2002.0,7.9,0,-30.915039,245
1748,F. Gary Gray,349.0,161.029270,Biography|Crime|Drama|History|Music,Aldis Hodge,Straight Outta Compton,119928,331.0,English,28.00,2015.0,7.9,76000,133.029270,246
788,Cameron Crowe,149.0,32.522352,Adventure|Comedy|Drama|Music,Philip Seymour Hoffman,Almost Famous,207287,822.0,English,60.00,2000.0,7.9,15000,-27.477648,247
639,Michael Mann,209.0,28.965197,Biography|Drama|Thriller,Al Pacino,The Insider,133526,521.0,English,68.00,1999.0,7.9,0,-39.034803,248
525,Alfonso Cuarón,372.0,35.286428,Drama|Sci-Fi|Thriller,Charlie Hunnam,Children of Men,361767,1206.0,English,76.00,2006.0,7.9,17000,-40.713572,249

In [104]:
 # Write your code to extract top foreign language films from 'IMDb_Top_250' here
Top_Foreign_Lang_Film=pd.DataFrame(IMDb_Top_250.loc[IMDb_Top_250['language']!='English',:])
Top_Foreign_Lang_Film

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,rank
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000,1966.0,8.9,20000,4.900000,5
4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000,2002.0,8.7,28000,4.263397,14
4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000,1954.0,8.7,11000,-1.730939,17
2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.000000,2001.0,8.6,28000,-8.950114,22
4259,Florian Henckel von Donnersmarck,215.0,11.284657,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000,2006.0,8.5,39000,9.284657,31
4921,Majid Majidi,46.0,0.925402,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,0.180000,1997.0,8.5,0,0.745402,42
4105,Chan-wook Park,305.0,2.181290,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000,2003.0,8.4,43000,-0.818710,46
1298,Jean-Pierre Jeunet,242.0,33.201661,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,77.000000,2001.0,8.4,39000,-43.798339,49
2970,Wolfgang Petersen,96.0,11.433134,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,14.000000,1981.0,8.4,11000,-2.566866,53
4659,Asghar Farhadi,354.0,7.098492,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,0.500000,2011.0,8.4,48000,6.598492,55
1329,S.S. Rajamouli,44.0,6.498000,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,18.026148,2015.0,8.4,21000,-11.528148,57
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809,59
4033,Thomas Vinterberg,349.0,0.610968,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000,2012.0,8.3,60000,-3.189032,72
2734,Fritz Lang,260.0,0.026435,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000,1927.0,8.3,12000,-5.973565,79
2829,Oliver Hirschbiegel,192.0,5.501940,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,13.500000,2004.0,8.3,14000,-7.998060,84
2551,Guillermo del Toro,406.0,37.623143,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,13.500000,2006.0,8.2,27000,24.123143,85
3550,Denis Villeneuve,226.0,6.857096,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000,2010.0,8.2,37000,0.057096,90
4000,Juan José Campanella,262.0,20.167424,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.000000,2009.0,8.2,33000,18.167424,95
2047,Hayao Miyazaki,212.0,4.710455,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,24.000000,2004.0,8.2,13000,-19.289545,100
2914,Je-kyu Kang,86.0,1.110186,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,12.800000,2004.0,8.1,0,-11.689814,112
3553,José Padilha,142.0,0.008060,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.000000,2007.0,8.1,11000,-3.991940,115
2830,Alejandro Amenábar,157.0,2.086345,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,10.000000,2004.0,8.1,0,-7.913655,126
4267,Alejandro G. Iñárritu,157.0,5.383834,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.000000,2000.0,8.1,11000,3.383834,141
4461,Thomas Vinterberg,98.0,1.647780,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000,1998.0,8.1,5000,0.347780,143
3423,Katsuhiro Ôtomo,150.0,0.439162,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.000000,1988.0,8.1,0,-1099.560838,146
4897,Sergio Leone,122.0,3.500000,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,0.200000,1964.0,8.0,0,3.300000,164
3344,Karan Johar,210.0,4.018695,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,12.000000,2010.0,8.0,27000,-7.981305,165
4144,Walter Salles,71.0,5.595428,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.900000,1998.0,8.0,0,2.695428,175
3456,Vincent Paronnaud,242.0,4.443403,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.300000,2007.0,8.0,14000,-2.856597,178
4284,Ari Folman,231.0,2.283276,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.500000,2008.0,8.0,0,0.783276,193
3264,Michael Haneke,447.0,0.225377,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.900000,2012.0,7.9,33000,-8.674623,214
4415,Fabián Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125.0,Spanish,1.500000,2000.0,7.9,0,-0.278739,219
3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.500000,2004.0,7.9,0,-1.870242,220
4640,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.590000,2007.0,7.9,14000,0.595783,225
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.000000,2004.0,7.9,2000,-4.078262,232
2863,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.000000,2006.0,7.9,5000,-5.246069,233
2493,Yimou Zhang,283.0,0.084961,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.000000,2002.0,7.9,0,-30.915039,244
1171,Yimou Zhang,283.0,0.084961,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.000000,2002.0,7.9,0,-30.915039,245

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [105]:
# Write your code for extracting the top 10 directors here
#b11 i tookjust a random number so ican breakthecodeintohalf for myeasiness
#copy function will makethe 
b11=movies.groupby(by='director_name').mean().copy()
top10director=b11.sort_values(by='imdb_score',ascending=False)
top10director=pd.DataFrame(top10director.head(10))
top10director

,num_critic_for_reviews,gross,num_voted_users,num_user_for_reviews,budget,title_year,imdb_score,movie_facebook_likes,profit
director_name,,,,,,,,,
Charles Chaplin,120.00,0.163245,1.430860e+05,211.000000,1.500000,1936.000000,8.600000,0.000000,-1.336755
Tony Kaye,162.00,6.712241,7.824370e+05,1420.000000,7.500000,1998.000000,8.600000,35000.000000,-0.787759
Damien Chazelle,535.00,13.092000,3.991380e+05,731.000000,3.300000,2014.000000,8.500000,129000.000000,9.792000
Ron Fricke,115.00,2.601847,2.245700e+04,69.000000,4.000000,2011.000000,8.500000,26000.000000,-1.398153
Alfred Hitchcock,290.00,32.000000,4.224320e+05,1040.000000,0.806947,1960.000000,8.500000,18000.000000,31.193053
Majid Majidi,46.00,0.925402,2.788200e+04,130.000000,0.180000,1997.000000,8.500000,0.000000,0.745402
Sergio Leone,138.00,4.966667,2.906917e+05,503.333333,10.466667,1971.333333,8.433333,10666.666667,-5.500000
Christopher Nolan,511.25,226.653447,1.013285e+06,2424.875000,125.625000,2007.125000,8.425000,103625.000000,101.028447
Marius A. Markevicius,26.00,0.133778,3.086000e+03,9.000000,0.500000,2012.000000,8.400000,0.000000,-0.366222
S.S. Rajamouli,44.00,6.498000,6.275600e+04,410.000000,18.026148,2015.000000,8.400000,21000.000000,-11.528148

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [106]:
# Write your code for extracting the first two genres of each movie here
#movies6just a copy soour orignaldata dosent get lost .i feelsafer to have copy and then use it 
#str.split str is added so that there is difference between normal split by python and pandas
#n=3because n starts from -1 to 0 -1 split then 0 to1 - 2nd split and then 1 to 2 -3rd split  andexpand =True means do you want to convert to different columns
movies6=movies.copy()
cc=movies6.genres.str.split('|',n=3,expand=True)
movies6['genre1']=cc[0]
movies6['genre2']=cc[1]
movies6['genre3']=cc[2]

In [107]:
 # Write your code for grouping the dataframe here
    #nouse of genre 3 
movies6=movies6.drop('genre3',axis=1)

In [108]:
#some ofthe moves had only 1 genre so when we splitted it it become null
#now filling those null values 
movies6.loc[movies6.genre2.isnull(),'genre2']=movies6.genre1
movies6

#PopGenre = # Write your code for getting the 5 most popular combo of genres here
movies6.groupby(['genre1','genre2']).gross.mean()
PopGenre=pd.DataFrame(movies6.groupby(['genre1','genre2']).gross.mean())
PopGenre=PopGenre.sort_values(by='gross',ascending=False)
PopGenre

                              gross
genre1      genre2
Family      Sci-Fi       434.949459
Adventure   Sci-Fi       228.627758
            Animation    116.998550
            Family       116.520833
Action      Adventure    110.382547
Fantasy     Mystery      100.614858
Animation   Comedy        97.781776
Action      Animation     92.680515
Musical     Romance       92.084000
Adventure   Drama         91.501214
            Fantasy       90.617977
Action      Mystery       90.330206
Animation   Family        86.266929
Action      War           77.086030
Animation   Drama         74.196576
Adventure   Mystery       72.099336
Action      Thriller      71.553674
            Sci-Fi        70.788280
Crime       Romance       69.304264
Comedy      Family        68.585147
Action      Romance       67.631157
Adventure   Adventure     67.163286
Drama       Western       67.103958
Crime       Thriller      62.602805
Romance     Sci-Fi        62.453315
Action      Action        59.520907
Fantasy     Romance       56.362352
Comedy      Western       56.003641
Adventure   Comedy        55.843581
Action      Drama         55.567259
...                             ...
Adventure   Crime         22.447493
Action      Family        22.059952
Comedy      Mystery       21.849314
Adventure   Biography     19.542570
Comedy      Documentary   19.306299
Drama       Drama         18.866271
Mystery     Romance       15.957533
Western     Western       15.914589
Comedy      Musical       13.703717
Action      Western       13.264986
Crime       Horror        13.240496
Comedy      Horror        12.443240
Family      Music         10.411980
Crime       Documentary    7.173562
Action      Sport          7.009668
Documentary Documentary    5.878533
Adventure   Documentary    3.761895
Documentary History        3.670846
Animation   Biography      3.363339
Family      Fantasy        2.119994
Fantasy     Thriller       1.487477
Documentary War            1.430185
Biography   Documentary    1.097735
Comedy      History        0.634277
Documentary Sport          0.600697
Horror      Musical        0.140244
Romance     Romance        0.102850
Thriller    Thriller       0.040513
Sci-Fi      Sci-Fi         0.018195
Adventure   War            0.014873

[103 rows x 1 columns]

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [109]:
# Write your code for creating three new dataframes here

Meryl_Streep=pd.DataFrame(movies.loc[movies['actor_1_name']=='Meryl Streep',:])

In [110]:
Leo_Caprio=pd.DataFrame(movies.loc[movies['actor_1_name']=='Leonardo DiCaprio',:])

In [111]:
Brad_Pitt=pd.DataFrame(movies.loc[movies['actor_1_name']=='Brad Pitt',:])

In [112]:
# Write your code for combining the three dataframes here
#ignore index is true because we want the index shouldnt overlap when we are appending means it shouldnt be 01234then again when we append 0123401234
Meryl_Streep.append(Leo_Caprio,ignore_index=True)
Brad_Pitt=Brad_Pitt.append(Meryl_Streep,ignore_index=True)

In [113]:
# Write your code for grouping the combined dataframe here
combined=Brad_Pitt.append(Leo_Caprio,ignore_index=True)
combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,Steven Soderbergh,186.0,183.405771,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.405771
1,Doug Liman,233.0,186.336103,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.336103
2,Neil Jordan,120.0,105.264608,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.264608
3,David Ayer,406.0,85.707116,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.707116
4,Steven Soderbergh,198.0,125.531634,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.531634
5,Alejandro G. Iñárritu,285.0,34.300771,Drama,Brad Pitt,Babel,243799,908.0,English,25.0,2006.0,7.5,0,9.300771
6,Andrew Dominik,414.0,14.938570,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15.0,2012.0,6.2,20000,-0.061430
7,Tony Scott,122.0,12.281500,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13.0,1993.0,8.0,15000,-0.718500
8,Angelina Jolie Pitt,131.0,0.531009,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10.0,2015.0,5.3,0,-9.468991
9,Terrence Malick,584.0,13.303319,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32.0,2011.0,6.7,39000,-18.696681
10,David Fincher,362.0,127.490802,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150.0,2008.0,7.8,23000,-22.509198
11,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.0,1999.0,8.8,48000,-25.976605
12,Andrew Dominik,273.0,3.904982,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30.0,2007.0,7.5,0,-26.095018
13,Jean-Jacques Annaud,76.0,37.901509,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70.0,1997.0,7.0,0,-32.098491
14,Patrick Gilmore,98.0,26.288320,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60.0,2003.0,6.7,880,-33.711680
15,Wolfgang Petersen,220.0,133.228348,Adventure,Brad Pitt,Troy,381672,1694.0,English,175.0,2004.0,7.2,0,-41.771652
16,Tony Scott,142.0,0.026871,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92.0,2001.0,7.0,0,-91.973129
17,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.732962
18,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.100000
19,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.125426
20,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.536011
21,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.703470
22,Phyllida Lloyd,331.0,29.959436,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13.0,2011.0,6.4,18000,16.959436
23,Stephen Daldry,174.0,41.597830,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25.0,2002.0,7.6,0,16.597830
24,Robert Altman,211.0,20.338609,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10.0,2006.0,6.8,683,10.338609
25,Curtis Hanson,42.0,46.815748,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45.0,1994.0,6.3,0,1.815748
26,Carl Franklin,64.0,23.209440,Drama,Meryl Streep,One True Thing,9283,112.0,English,30.0,1998.0,7.0,592,-6.790560
27,Robert Redford,227.0,14.998070,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35.0,2007.0,6.2,0,-20.001930
28,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
29,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.568851
30,Steven Spielberg,194.0,164.435221,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.435221
31,Quentin Tarantino,765.0,162.804648,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.804648
32,Alejandro G. Iñárritu,556.0,183.635922,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.635922
33,Martin Scorsese,490.0,127.968405,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80.0,2010.0,8.1,53000,47.968405
34,Martin Scorsese,352.0,132.373442,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90.0,2006.0,8.5,29000,42.373442
35,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105.0,2013.0,7.3,115000,39.812796
36,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105.0,2013.0,7.3,115000,39.812796
37,Baz Luhrmann,106.0,46.338728,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14.5,1996.0,6.8,10000,31.838728
38,Randall Wallace,83.0,56.876365,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35.0,1998.0,6.4,0,21.876365
39,Martin Scorsese,606.0,116.866727,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100.0,2013.0,8.2,138000,16.866727
40,Clint Eastwood,392.0,37.304950,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35.0,2011.0,6.6,16000,2.304950
41,Martin Scorsese,267.0,102.608827,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110.0,2004.0,7.5,0,-7.391173
42,Jerry Zaks,45.0,12.782508,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23.0,1996.0,6.7,1000,-10.217492
43,Danny Boyle,118.0,39.778599,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50.0,2000.0,6.6,0,-10.221401
44,Sam Mendes,323.0,22.877808,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35.0,2008.0,7.3,0,-12.122192
45,Sam Raimi,63.0,18.636537,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32.0,1995.0,6.4,0,-13.363463
46,Martin Scorsese,233.0,77.679638,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100.0,2002.0,7.5,0,-22.320362
47,Ridley Scott,238.0,39.380442,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70.0,2008.0,7.1,0,-30.619558
48,Edward Zwick,166.0,57.366262,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100.0,2006.0,8.0,14000,-42.633738

In [114]:
# Write the code for finding the mean of critic reviews and audience reviews here
combined.groupby(by='actor_1_name')['num_critic_for_reviews','num_user_for_reviews'].mean()

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Brad Pitt                      245.000000            742.352941
Leonardo DiCaprio              330.190476            914.476190
Meryl Streep                   181.454545            297.181818

**Checkpoint 6:** `Leonardo` has aced both the lists!